### ISSUE TITLE
HEAT_STATE vs 0.90.0

### ISSUE THREAD

**Issue by radinsky** [vpnmaster/homeassistant-custom-components#123]
After upgrading to 0.90 the component is failing to load:
```
2019-03-07 17:19:23 ERROR (SyncWorker_15) [homeassistant.loader] Error loading custom_components.broadlink.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/broadlink/climate.py", line 10, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'STATE_HEAT' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py)
2019-03-07 17:19:23 ERROR (SyncWorker_15) [homeassistant.loader] Error loading custom_components.climate.broadlink. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/climate/broadlink.py", line 10, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'STATE_HEAT' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py)
2019-03-07 17:19:23 ERROR (SyncWorker_15) [homeassistant.loader] Unable to find platform broadlink.
```
