### ISSUE TITLE
Breaking change on 0.89.1

### ISSUE THREAD

**Issue by dclobato** [vpnmaster/homeassistant-custom-components#124]
I suspect that release 0.89.1 of home assistant broke this component. It was working on 0.86

```
2019-03-08 15:05:16 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.climate.broadlink. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/climate/broadlink.py", line 10, in <module>
    from homeassistant.components.climate import (ClimateDevice, PLATFORM_SCHEMA, STATE_OFF, STATE_IDLE, STATE_HEAT, STATE_COOL, STATE_AUTO,
ImportError: cannot import name 'STATE_IDLE' from 'homeassistant.components.climate' (/usr/src/app/homeassistant/components/climate/__init__.py)
2019-03-08 15:05:16 ERROR (MainThread) [homeassistant.loader] Unable to find platform broadlink.
```

**Comment by alattincakici** [comment]
same here HASSIO 0.89.1:

2019-03-09 10:03:34 ERROR (SyncWorker_5) [homeassistant.loader] Error loading custom_components.climate.broadlink. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/climate/broadlink.py", line 11, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'SUPPORT_TARGET_TEMPERATURE' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py)
2019-03-09 10:03:34 ERROR (SyncWorker_5) [homeassistant.loader] Unable to find platform broadlink.

**Comment by earth08** [comment]
i solved this by putting broadlink.py provided by homeassitant as component in /custom_components/broadlink/switch.py
i changed name of broadlink.py to switch.py
it does gave me working broadlink.switch
but my climate is not working ( climate entity is not even found)

**Comment by kylegordon** [comment]
0.87 changed the way Home-Assistant handles components - you can read more at https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html

I had to change my Broadlink Mini 3 'media player' file to exist at custom_components/broadlink/media_player.py instead. You may have some luck calling it climate.py

In saying all that, I see https://github.com/vpnmaster/homeassistant-custom-components/blob/master/README.md is telling us that it's all deprecated, and we should instead be using https://github.com/smartHomeHub/SmartIR
